$(function(){
	$("#CheckForm").validate({
		rules:{
			"login_userName":{
				"required":true,
				"minlength":3,
				"maxlength":12,
				"check_login_userName":true,
			},
			"login_userName2":{//这个没作用，原因不明
				"required":true,
				"minlength":3,
				"maxlength":12,
			},
			"login_password":{
				"required":true,
				"minlength":6,
				"maxlength":15,
			},
			"login_password1":{
				"required":true,
				"equalTo":"[name='login_password']"
			},
			"login_email":{
				"required":true,
				"email":true
			},
			"login_phone":{
				"required":true,
				"digits":true,
				"minlength":11,
				"maxlength":11,
			},
			"login_sex":{
				
			},
			"checkCode":{
				"required":true,
				"check_checkCode":true,
				//equalTo:"[name='checkCode2']"
			},
		},
	messages:{

		"login_userName":{
			"required":"用户名不能为空!",
			"minlength":"用户名不得少于3位!",
			"maxlength":"用户名不得多于5位!",
			"check_login_userName":"用户名已存在",
		},
		"login_userName2":{
			"required":"用户名不能为空!",
			"minlength":"用户名不得少于3位!",
			"maxlength":"用户名不得多于5位!",
		},
		"login_password":{
			"required":"密码不能为空!",
			"minlength":"密码不能少于6位!",
			"maxlength":"密码不能超过15位!",
			
		},
		"login_password1":{
			"required":"密码不能为空!",
			"equalTo":"两次输入密码不一致!",
		},
		"login_email":{
			"required":"邮箱不能为空!",
			"email":"请输入有效的电子邮件地址",
		},
		"login_phone":{
			"required":"手机号不能为空!",
			"digits":"只能输入数字",
			"minlength":"手机号必须为11位!",
		},
		"login_sex":{	
			
		},
		"checkCode":{
			"required":"验证码不能为空!",
			"check_checkCode":"验证码输入错误",
		},
	  },
	});
});